site_name: Promobot Appeal Processing
site_author: KruASe

repo_name: digital-fracture/promobot-appeal-processing
repo_url: https://github.com/digital-fracture/promobot-appeal-processing

copyright: Copyright &copy; 2023 digital-fracture

theme:
    name: material
    features:
        - content.code.copy
        - content.code.annotate
    palette:
        scheme: slate
        primary: green
        accent: pink
    font:
        text: Inter
        code: JetBrains Mono
    language: en

markdown_extensions:
    - pymdownx.highlight:
        line_spans: __span
        pygments_lang_class: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
    - attr_list
    - pymdownx.emoji:
        emoji_index: !!python/name:material.extensions.emoji.twemoji
        emoji_generator: !!python/name:material.extensions.emoji.to_svg
    - toc:
        permalink: true

plugins:
    - mkdocstrings:
        handlers:
            python:
                paths: [src]
                options:
                    heading_level: 3
                    show_root_heading: true
                    show_root_full_path: false
                    show_signature_annotations: true
                    show_if_no_docstring: true
                    merge_init_into_class: true
                    docstring_section_style: list
                    members_order: source

extra_css:
    - stylesheets/extra.css
